#include <stdio.h> 
#include <stdlib.h> 
#include <unistd.h> 
#include <string.h> 
#include <sys/types.h> 
#include <sys/socket.h> 
#include <arpa/inet.h> 
#include <netinet/in.h> 
int sock;
struct sockaddr_in addr;
char buffer[100], buffer1[100];
void sendm(char *msg, int length)
{
    sendto(sock, msg, length, 0, (struct sockaddr *) &addr,sizeof(addr));
} 
void readm()
{
    
    int len = sizeof(addr);
    int n=recvfrom(sock, (char *)buffer, sizeof(buffer), 0, ( struct sockaddr *) &addr, &len); 
    buffer[n]='\0';
}
int enc(int m, int e, int n)
{
    return fnPow(e, m, n);    
}
char* itoa(int n)
{
	sprintf(buffer1, "%d", n);
	return buffer1;
}
int fnPow(int a, int b, int c)
{
    int res = 1, i;
    for(i=0;i<a;i++)
    {
        res *= b;
        res %= c;
    }
    return res;
}
int main()
{	
	srand(time(NULL));
	int noncec = rand()%100;
    char buf[2];
	struct sockaddr_in addr1 = { AF_INET, htons(1237), INADDR_ANY };
    addr=addr1;
	sock = socket(AF_INET, SOCK_DGRAM, 0);
	connect(sock, (struct sockaddr*)& addr, sizeof(addr));
	
	sendm("7", 1);
    sendm("143", 3);
	readm();
	int prb = 103;
	int id = enc(buffer[0], prb, 143);
	int nonces = enc(buffer[1], prb, 143);
	printf("\nreceived server_id=%d\nnonce received from server=%d\n",id, nonces);
	printf("\n nonce generated by client = %d\n", noncec);
	
	readm();
	int pus =atoi(buffer);
	readm();
	int nn = atoi(buffer);
	int prc=103;
	
	buffer[0]=enc(nonces, pus, nn);;
	buffer[1]=enc(noncec, pus, nn);;
	sendm(buffer, 2);
	
	readm();
	printf("Client nonce received from server = %d\n", buffer[0]);
	
	readm();
	printf("Received encrypted key: %d \n", buffer[0]);
	int key = enc(buffer[0], prc, 143);
	key = enc(key, pus, 143);
	printf("Received decrypted key: %d \n", key);

	close(sock);
	return 0;
}
