#include <stdio.h> 
#include <stdlib.h> 
#include <unistd.h> 
#include <string.h> 
#include <sys/types.h> 
#include <sys/socket.h> 
#include <arpa/inet.h> 
#include <netinet/in.h> 
int sock;
char buffer[100], buffer1[100];
struct sockaddr_in addr;
void sendm (char *msg, int length)
{
    sendto(sock, msg, length, 0, (struct sockaddr *) &addr,sizeof(addr));
}
int fnPow(int a, int b, int c)
{
    int res = 1, i;
    for(i=0;i<a;i++)
    {
        res *= b;
        res %= c;
    }
    return res;
}
void readm()
{
    
    int len = sizeof(addr);
    int n=recvfrom(sock, (char *)buffer, sizeof(buffer), 0, ( struct sockaddr *) &addr, &len); 
	buffer[n]='\0';
    return buffer;
}
int enc(int m, int e, int n)
{
    return fnPow(e, m, n);    
}
char* itoa(int n)
{
	sprintf(buffer1, "%d", n);
	return buffer1;
}

int main()
{   
	srand(time(NULL));
	int sid, nonces = rand()%100, key;
	char buf[2];
    struct sockaddr_in addr1 = { AF_INET, htons(1237), INADDR_ANY }; 
    addr=addr1;
	
	
	sock = socket(AF_INET, SOCK_DGRAM, 0);
	
	bind(sock, (struct sockaddr*)&addr, sizeof(addr));
	
	readm();
	int puc =atoi(buffer);
	readm();
	int n = atoi(buffer);
	
	printf("Received Public key ( %d, %d )\n", puc, n);
	printf("Enter server ID <100: ");
	scanf("%d", &sid);
	printf("server_id = %d\nnonce generated by server = %d\n", sid, nonces);
	
	buf[0]=enc(sid, puc, n), buf[1]=enc(nonces, puc, n);
	sendm(buf, 2);
	
	
	sendm("7", 2);
	sendm("143", 3);
	
	readm();
	int prs = 103;
	int ns = enc(buffer[0], prs, 143);
	int noncec = enc(buffer[1], prs, 143);
	printf("\nserver nonce received from client=%d\nnonce received from client=%d\n",ns, noncec);
	
	buffer[0] = noncec;
	sendm(buffer, 1);
	
	printf("Enter Secret key: ");
	scanf("%d", &key);
	key = enc(key, prs,143);
	key = enc(key, puc,143);
	
	buffer[0]=key;
	sendm(buffer, 1);
	
	
	
	return 0;
}